[package]
name = "pinocchio_flash_loan"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.10.1"
pinocchio-system = "0.5.0"
pinocchio-token = "0.5.0"

[lib]
crate-type = ["lib", "cdylib"]